# Generated by Django 3.2 on 2021-08-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('start_point', models.CharField(max_length=20)),
                ('end_point', models.CharField(max_length=20)),
            ],
        ),
    ]
