# Generated by Django 3.2 on 2021-08-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
